name: Enhancement
description: Form for an enhancement, new feature or request
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the enhancement
      description: A concise description of the feature you are requesting.
    validations:
      required: false
      placeholder: |
        Description of the feature.

        ```python
        # Possible pseudo code to describe the feature
        ```
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false